spring.application.name=generative_art_world
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:genartdb}
spring.datasource.username=${DB_USER:genart}
spring.datasource.password=${DB_PASSWORD:genart}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
